### ISSUE TITLE
Armar estructura de la presentación

### ISSUE THREAD

**Issue by manuporto** [hydro-monitor/node#115]
- Explicar el requerimiento que nos llevó a elegir Cassandra.
- Detallar pruebas que se hicieron y los resultados.
- Contar de qué es Cassandra, explicar didácticamente.
- Seguridad (https, jwt, roles de usuario y nodos, usuarios de cassandra y sus roles)
- Nodo (componentes)

**Comment by abrden** [comment]
Link: https://docs.google.com/presentation/d/1OK2hqzv6hVs-PNFP58fAdxmKeL0z-hW5u8c3ts-TFj4/edit?usp=sharing
