### ISSUE TITLE
Fundamentar elección de herramientas

### ISSUE THREAD

**Issue by manuporto** [hydro-monitor/node#116]
Cassandra, Go, React, etc.

**Comment by aibarbetta** [comment]
* https://golangbot.com/goroutines/
* https://golang.org/ref/mem
* https://www.crazyleafdesign.com/blog/why-javascript-is-important-for-web-developers/
* https://www.c-sharpcorner.com/article/what-and-why-reactjs/
* https://material-ui.com/es/
* https://material.io/design/introduction
* https://www.geeksforgeeks.org/disadvantages-of-java-language/
* https://github.com/gocql/gocql
* https://gocql.github.io/
* https://spiralscout.com/blog/when-to-use-go-vs-java-one-programmers-take-on-two-top-languages
* https://cassandra.apache.org/
* https://www.haproxy.org/
