### ISSUE TITLE
Integrar GetNodeConfiguration() con servidor

### ISSUE THREAD

**Issue by abrden** [hydro-monitor/node#41]

**Comment by abrden** [comment]
@manuporto Este endpoint esta hecho o tiene mock?

**Comment by manuporto** [comment]
Está mockeado todavía

**Comment by abrden** [comment]
Podes hacer que el mock me devuelva esto? https://my-json-server.typicode.com/hydro-monitor/web-api-mock/configurations/1

**Comment by manuporto** [comment]
Ya devuelve eso el mock, salvo el id de la configuración que es medio redundante porque está en la ruta. Tambien los nombres de las keys están en minuscula

**Comment by abrden** [comment]
10/10

**Comment by abrden** [comment]
- [ ] Integrar con server
- [ ] Cubrir caso en el que el nodo no tenga configuración cargada

**Comment by abrden** [comment]
- [ ] Probar análisis de estado actual arreglando configuración mockeada en server

**Comment by abrden** [comment]
Links de prueba:
* https://my-json-server.typicode.com/hydro-monitor/web-api-mock/requests/1
* https://my-json-server.typicode.com/hydro-monitor/web-api-mock/configurations/1
