### ISSUE TITLE
Integrar GetManualMeasurementRequest() con servidor

### ISSUE THREAD

**Issue by abrden** [hydro-monitor/node#42]

**Comment by abrden** [comment]
@manuporto Este endpoint esta hecho o tiene mock?

**Comment by manuporto** [comment]
La información está cuando pedís la información del nodo. Lo que no está es el endpoint para cambiar la variable de manual reading.

**Comment by abrden** [comment]
Necesitaría un endpoint como https://my-json-server.typicode.com/hydro-monitor/web-api-mock/requests/1 que es lo que pusimos en el doc de arquitectura

**Comment by abrden** [comment]
Despues para avisar que esa medida manual ya fue tomada, lo que hago es mandarte un booleano wasManual en el post de medicion

**Comment by abrden** [comment]
Habria que inicializar esto en false cuando se haga una creación de un nuevo nodo, de lo contrario me pasa esto al hacer el get de un nodo desconocido para el server
```
E0204 07:31:05.849817    1640 manual.go:34] Could not get manual measurement request from server: invalid character 'o' in literal null (expecting 'u')
```
@manuporto
